add -p command's h/ prefix does not run properly
AY2223S1-CS2103-W14-1/tp pull request #190
Opened 2022-10-29 07:08 UTC by yuehernkang

Will default to `AVAILABLE` status if not specified in the command

2022-10-29 07:09 UTC, yuehernkang commented
closes #185

2022-10-29 18:43 UTC, yuehernkang commented
closes #174

2022-10-29 19:15 UTC, yuehernkang commented
closes #146

2022-10-29 19:17 UTC, yuehernkang commented
closes #148

2022-10-29 19:30 UTC, yuehernkang commented
closes #133

2022-10-29 19:30 UTC, yuehernkang commented
closes #132

2022-10-31 09:03 UTC, lkwlkww approved these changes

2022-11-01 15:12 UTC, misterpuffin commented on src/main/java/seedu/condonery/logic/parser/ParserUtil.java
> +        return PropertyStatusEnum.valueOf(propertyStatus) == null
I think this conditional doesn't make sense. valueOf will never return a null value but instead throw IllegalArgumentException, which you will need to catch and throw a ParseException, as stated in the method signature.

You can look at the parsePropertyType function as reference for how I previously catch the error. For example, the command `add -p a/Duxton n/Duxton p/10000 h/hdb s/INVALID VALUE` will cause the application to throw an Exception.

2022-11-01 15:18 UTC, misterpuffin requested changes
actually can refer to my pr here! https://github.com/AY2223S1-CS2103-W14-1/tp/pull/118/files

2022-11-02 08:25 UTC, zacchaeuschok approved these changes
LGTM

2022-11-02 08:33 UTC, merged