filter -p command format should be on the new line
AY2223S1-CS2103-W14-1/tp pull request #192
Opened 2022-10-29 07:30 UTC by yuehernkang

2022-10-29 15:09 UTC, yuehernkang commented
closes #159

2022-10-31 09:15 UTC, lkwlkww approved these changes

2022-11-01 15:14 UTC, misterpuffin requested changes
would approve the UG changes but can change the ParserUtil files? In general might be good to keep your PR's separate!

2022-11-02 09:20 UTC, zacchaeuschok approved these changes

2022-11-03 05:03 UTC, lkwlkww approved these changes

2022-11-05 08:26 UTC, misterpuffin approved these changes
lgtm!

2022-11-05 09:49 UTC, closed without merging