Add price range command
AY2223S1-CS2103-W14-1/tp pull request #88
Opened 2022-10-20 07:26 UTC by zacchaeuschok

2022-10-22 19:31 UTC, lkwlkww approved these changes

2022-10-23 07:21 UTC, yuehernkang commented on src/test/data/JsonSerializablePropertyDirectoryTest/typicalPropertyDirectory.json
> +      "price": "1,000,000",
Will the data automatically include commas when saving? I think we should leave it as a number.

2022-10-23 07:23 UTC, yuehernkang commented on src/main/java/seedu/condonery/model/property/Price.java
> +    public final String value;
If price is string do we need to always convert back to `int` when performing manipulations such as below or above a certain price? Would `int` type be better?

2022-10-23 07:24 UTC, yuehernkang requested changes
Price data type discussion

2022-10-23 08:30 UTC, yuehernkang approved these changes

2022-10-23 08:31 UTC, merged